### ISSUE TITLE
[Front] Alteração de situação de escolas

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-Front#17]
## Implementação
Deve-se realizar a atualização da implementação da tela de visualização de escolas seguindo o protótipo definido na tarefa [#64](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/issues/64).  Além disso, deve-se atualizar a tela de visualização com a nova situação.

## D.O.D
- [x] Deve-se estar condizente com o protótipo
- [x] Print da tela rodando localmente
- [x] Comunicação com o endpoint do backend
- [x] Atualização da tela de visualização

**Comment by CarolinaBarb** [comment]
Adicionando situação
![Image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/98655636/f596f86e-e8c3-43d1-9f44-5c4221f73551)

Listando informação das escolas
![Image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/98655636/34a0d43e-c8b5-444d-b5b7-3f2fc834dcd1)
