### ISSUE TITLE
[Front] Remoção de situação de escolas

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-Front#18]
## Implementação
Deve-se realizar a atualização da implementação da tela de visualização de escolas seguindo o protótipo definido na tarefa [#65](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/issues/65).  Além disso, deve-se atualizar a tela de visualização com a nova situação.

## D.O.D
- [x] Deve-se estar condizente com o protótipo
- [x] Print da tela rodando localmente
- [x] Comunicação com o endpoint do backend
- [ ] Atualização da tela de visualização

**Comment by GuilhermeSoaress** [comment]
![Image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88786065/04500727-cafe-423f-a91e-97a94767aaa8)


![Image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88786065/290f78f7-e0b6-483e-91b2-936f0de67d06)
