### ISSUE TITLE
[BUG] Validação de senha e email na area de cadastro

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-Front#22]
O campo de senha e email estão sem validação
- [x] campo de email deve acusar quando não estiver em formato correto
- [x] campo de senha deve acusar quando as senhas não forem iguais

**Comment by antoniotoineto** [comment]
[PR](https://github.com/fga-eps-mds/2023.1-Dnit-Front/pull/25) aberto para essa issue
