### ISSUE TITLE
[Front] Testes

### ISSUE THREAD

**Issue by isadoragalvaoss** [fga-eps-mds/2023.1-Dnit-Front#35]
## Implementação
Fazer testes para todos os cenários

## D.O.D
- [x] Deve estar acima de 80% no coverage
- [x] Deve ser feito para todas as telas
- [x] Deve ser aprovado no sonar

**Comment by antoniotoineto** [comment]
Foram feitos a Implementação de testes e ajustes necessários para passar na análise de qualidade do Sonar
