### ISSUE TITLE
[Front] Aprimoramento de tela de exclusão de escolas

### ISSUE THREAD

**Issue by antoniotoineto** [fga-eps-mds/2023.1-Dnit-Front#45]
Vamos realizar alguns pontos a serem melhorados na tela de exclusão de escolas
- [x] Fechar o modal quando uma escola for excluída com sucesso
- [x] Colocar mensagem de aviso de sucesso ou falha

**Comment by lhuck4z** [comment]
![Image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/108501120/c37316c9-386a-426f-afad-a77797bd1e3c)


![Image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/108501120/1cd9b5ac-eb68-471f-8754-fd1e0e4993b1)
