### ISSUE TITLE
[Front] Melhorias e hotfix na tela de informações da escola

### ISSUE THREAD

**Issue by antoniotoineto** [fga-eps-mds/2023.1-Dnit-Front#57]
## D.O.D

- [x] Campo de observações funcional
- [x] Recolher dropdown na situação
- [x] Modal acompanhando a tela
- [x] Modal mais larga e sem scroll
- [x] Print das alterações rodando localmente

**Comment by CarolinaBarb** [comment]
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/98655636/a6aed01d-da08-4e9b-b52c-9a5283f94e4c)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/98655636/32ff51a2-91f4-40a0-b016-e60f663f84cb)
